version: "3"
services:
    nginx:
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        volumes:
            - ".:/var/www/html"
        networks:
            - internal
        depends_on:
            - php
    php:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        volumes:
            - ".:/var/www/html"
        networks:
            - internal
        depends_on:
            - mysql
    mysql:
        image: "mysql/mysql-server:8.0"
        restart: unless-stopped
        ports:
            - "${FORWARD_DB_PORT:-3306}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - "akaunting-db:/var/lib/mysql"
        networks:
            - internal
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s

volumes:
    akaunting-db:
networks:
    internal:
        driver: bridge
